# Generated by Django 2.1.1 on 2018-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
