# Generated by Django 2.1.1 on 2018-09-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20180915_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
    ]
