# Generated by Django 2.1.1 on 2018-09-15 17:59

from django.db import migrations, models
import quest.models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_remove_question_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_n',
            field=models.IntegerField(default=0, validators=[quest.models.nbr_limit]),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_y',
            field=models.IntegerField(default=0, validators=[quest.models.nbr_limit]),
        ),
    ]
