# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_time',
            new_name='pub_date',
        ),
    ]
