# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 9, 16, 11, 11, 44, 661010, tzinfo=utc)),
        ),
    ]
