# Generated by Django 2.0.8 on 2018-09-16 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180916_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 9, 16, 11, 12, 33, 517012, tzinfo=utc)),
        ),
    ]
