# Generated by Django 2.0.8 on 2018-09-16 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180916_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 9, 16, 12, 42, 56, 220393, tzinfo=utc)),
        ),
    ]
