# Generated by Django 2.0.8 on 2018-09-16 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180916_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coms', to='posts.Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 9, 16, 12, 47, 51, 651826, tzinfo=utc)),
        ),
    ]
