# Generated by Django 2.0.8 on 2018-09-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180916_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_key',
        ),
        migrations.AddField(
            model_name='posts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
